version: "3"
services:
  mongo:
    image: mongo
    container_name: "telzir-mongo"
    build: ./mongo
    restart: "always"
    #volumes:
      #- ./.dbcache/mongo/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: telzir
    networks:
      - backend
  api:
    image: node:10.16-slim
    container_name: "telzir-api"
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: bash -c "npm install && npm start"
    networks:
      - backend

  redis:
    image: redis:5.0.5-alpine
    container_name: "telzir-redis"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"