const ERR_USER_NOT_FOUND = 'USER_NOT_FOUND';
const ERR_INVALID_PASSWORD = 'INVALID_PASSWORD';
const ERR_INVALID_TOKEN = 'TOKEN_ERROR';

const ERR_DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';

const ERR_PLAN_NOT_FOUNT = 'PLAN_NOT_FOUND';
const ERR_FARE_NOT_FOUNT = 'FARE_NOT_FOUND';
const ERR_INVALID_TOTAL_MINUTUES = 'INVALID_TOTAL_MINUTUES';

const ERR_CUSTOMER_ALREADY_EXISTS = 'CUSTOMER_ALREADY_EXISTS';
const ERR_FARE_ALREADY_EXISTS = 'FARE_ALREADY_EXISTS';

module.exports = {
    ERR_USER_NOT_FOUND,
    ERR_INVALID_PASSWORD,
    ERR_INVALID_TOKEN,
    ERR_DUPLICATE_EMAIL,
    ERR_PLAN_NOT_FOUNT,
    ERR_FARE_NOT_FOUNT,
    ERR_INVALID_TOTAL_MINUTUES,
    ERR_CUSTOMER_ALREADY_EXISTS,
    ERR_FARE_ALREADY_EXISTS
};